AvatarPresets = {}

AvatarPresets.GenderBodyTypes = {
	
	["Male"] = {
		["Left Arm"] = Vector3.new(1,2,1),
		["Right Arm"] = Vector3.new(1,2,1),
		["Torso"] = Vector3.new(2,2,1),
		["Head"] = Vector3.new(2,1,1),
		["Right Leg"] = Vector3.new(1,2,1),
		["Left Leg"] = Vector3.new(1,2,1),
		
		Shirt = "http://www.roblox.com/asset/?id=113365253328410",
		Pants = "http://www.roblox.com/asset/?id=114405503597291"

	},
	["Female"] = {
		["Left Arm"] = Vector3.new(0.95,2,1),
		["Right Arm"] = Vector3.new(0.95,2,1),
		["Torso"] = Vector3.new(1.9,2,1),
		["Head"] = Vector3.new(2,1,1),
		["Right Leg"] = Vector3.new(0.98,2,1),
		["Left Leg"] = Vector3.new(0.98,2,1),
		
		Shirt = "http://www.roblox.com/asset/?id=14765856802",
		Pants = "http://www.roblox.com/asset/?id=5154291787"
		
	}
	
	
	
	
}


AvatarPresets.SkinColor = {
	[1] = Color3.fromRGB( 220, 245, 220),
	[2] = Color3.fromRGB(204, 142, 105),
	[3] = Color3.fromRGB(124, 92, 70),
	[4] = Color3.fromRGB(101, 67, 33),
}



return AvatarPresets